name: metrkoin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  get: ^4.6.5
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  image_picker: ^1.0.2
  google_fonts: ^5.1.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  pull_to_refresh: ^2.0.0
  google_mobile_ads: ^3.0.0
  #http: ^1.1.0
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
  provider: ^6.0.5

  # game_arena dependencies:
  sudoku_dart: ^1.1.0
  sprintf: ^7.0.0
  scoped_model: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/metrkoin.png"



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


